start: "2021-01-01T00:00:00Z"
end: "2021-01-01T00:00:00Z"
interval: 30
tags:
    - name: cluster
      type: String
      dist:
        type: constant_string
        value: eks-us-east-1-qa1
    - name: namespace
      type: String
      dist:
        type: replica_string
        replica: 18
        replica_prefix: app-
    - name: job
      type: String
      dist:
        type: constant_string
        value: kubelet-state-metrics
fields:
    - name: greptime_value
      type: Float
      dist:
        type: mono_inc
        lower_bound: 1
        upper_bound: 1000
        step: 10
