start: "2021-01-01T00:00:00Z"
end: "2021-01-01T00:00:00Z"
interval: 30
tags:
    - name: cluster
      type: String
      dist:
        type: constant_string
        value: eks-us-east-1-qa1
    - name: env
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: env0
              weight: 1
            - value: env1
              weight: 1
            - value: env2
              weight: 1
            - value: env3
              weight: 1
    - name: holiday
      type: String
      dist:
        type: constant_string
        value: "false"
    - name: namespace
      type: String
      dist:
        type: replica_string
        replica: 18
        replica_prefix: app-
    - name: prometheus
      type: String
      dist:
        type: constant_string
        value: monitoring/prometheus-kube-prometheus-prometheus
    - name: prometheus_replica
      type: String
      dist:
        type: constant_string
        value: prometheus-prometheus-kube-prometheus-prometheus-0
fields:
    - name: greptime_value
      type: Float
      dist:
        type: mono_inc
        lower_bound: 1
        upper_bound: 1000
        step: 10
