start: "2021-01-01T00:00:00Z"
end: "2021-01-01T00:00:00Z"
interval: 30
tags:
    - name: cluster
      type: String
      dist:
        type: constant_string
        value: eks-us-east-1-qa1
    - name: container
      type: String
      dist:
        type: constant_string
        value: container0
    - name: endpoint
      type: String
      dist:
        type: constant_string
        value: http-metrics
    - name: env
      type: String
      dist:
        type: constant_string
        value: qa
    - name: holiday
      type: String
      dist:
        type: constant_string
        value: "false"
    - name: hostname
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: hostname0
              weight: 1
            - value: hostname1
              weight: 1
            - value: hostname2
              weight: 1
    - name: instance
      type: String
      dist:
        type: replica_string
        replica: 1
        replica_prefix: instance-
    - name: instance_type
      type: String
      dist:
        type: constant_string
        value: t4g.large
    - name: job
      type: String
      dist:
        type: constant_string
        value: node-exporter
    - name: namespace
      type: String
      dist:
        type: replica_string
        replica: 18
        replica_prefix: app-
    - name: pod
      type: String
      dist:
        type: replica_string
        replica: 2
        replica_prefix: pod-
    - name: prometheus
      type: String
      dist:
        type: constant_string
        value: monitoring/prometheus-kube-prometheus-prometheus
    - name: prometheus_replica
      type: String
      dist:
        type: constant_string
        value: prometheus-prometheus-kube-prometheus-prometheus-0
    - name: region
      type: String
      dist:
        type: constant_string
        value: us-east-1
    - name: service
      type: String
      dist:
        type: constant_string
        value: prometheus-prometheus-node-exporter
    - name: zone
      type: String
      dist:
        type: constant_string
        value: us-east-1a
fields:
    - name: greptime_value
      type: Float
      dist:
        type: mono_inc
        lower_bound: 1
        upper_bound: 1000
        step: 10
