end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    type: weighted_preset
  name: container
  type: String
- dist:
    preset:
    - value: /dev/nvme2n1
      weight: 1
    type: weighted_preset
  name: device
  type: String
- dist:
    type: constant_string
    value: https-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pode5b24262_5e15_4ee2_b50d_6a23528a163d.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pode5b24262_5e15_4ee2_b50d_6a23528a163d.slice/cri-containerd-b153517b90d7f85f7e77235f1185274abddd12d14c387b92ca7aa62cdfc539aa.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podf491c71f_1804_4ac0_a150_ccc7009e94ea.slice/cri-containerd-83723ef720c1c95ed4228fe59e3667ef50d55e099b3ce07316f865a611984954.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod45a656b1_5b4f_4ea3_9471_51b83f6a18bc.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod144eb1a8_0735_4d5e_bffc_75b4c92086ca.slice/cri-containerd-b9afbc1ca38342723e7948d48f7033a976dcf5c4bb9bd2bb80d422fb4e74d5fe.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podd3ea6a07_4cf9_48a6_a773_116e0dfcecba.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb2f9100d_ea63_4555_9955_b24df842b7b1.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podbf27637f_3b38_47fb_9479_900854ecdc3d.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb7c39198_eff1_4a51_a7fb_d4550f3e0702.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podd947eed5_d0a1_48e4_b315_257ba5c5965d.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3589b6c1_9886_4b29_89ce_736888c6bbcd.slice/cri-containerd-b4022f119f874de41bfe389c5c7d6806950f17b62b0d4ae283bf1a2fbbb7c37c.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb815caae_7d3e_4c67_905b_4b642927a3bf.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda90b6015_2c50_4efd_abea_2bf1c47eaa52.slice/cri-containerd-811ef3eae0d0be45c7eca8ed72645697cd15d95135e4d0b373da9834f46d8df1.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6885b44c_57e5_4cda_b825_c866131ec44b.slice/cri-containerd-9684ead7dd6dc36ca81c8dc7f9fb363bf33ea7936e34535850013ee0510776f6.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod09b05b52_f4c9_4156_a2dd_4c6b6b3099c0.slice/cri-containerd-1225305fe001e9c73921d32581b7adfafc6768f8190bfcbfc7019f2b0ca829c8.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod09b05b52_f4c9_4156_a2dd_4c6b6b3099c0.slice/cri-containerd-da29c54ef3b1a6e02a9263d5ebab7dd1c82a4faf1b960ba48e69df0169f800c5.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod144eb1a8_0735_4d5e_bffc_75b4c92086ca.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod06d806d7_d72d_4cb1_8a53_ed9a3ff9cc6d.slice/cri-containerd-7feadb35f38918f16e55b9ed4c66016d22e6cc80110884121553ec644e6daf79.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod09b05b52_f4c9_4156_a2dd_4c6b6b3099c0.slice
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podfd522ff2_38da_4940_8c40_e6eb6a376168.slice/cri-containerd-2d1e5791229bb644f302c4c2a49cabf0bac0f3da3ec3888ea4f5ee9976a1ec54.scope
      weight: 1
    type: weighted_preset
  name: id
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: docker.io/bitnami/kafka:3.9.0-debian-12-r1
      weight: 1
    - value: quay.io/argoproj/argocd:v2.10.1
      weight: 1
    - value: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.34.0
      weight: 1
    - value: docker.io/timberio/vector:0.42.0-distroless-libc
      weight: 1
    - value: greptime-registry.cn-hangzhou.cr.aliyuncs.com/greptime/greptime-ent-cloud-dev:standalone-0227-weny-4
      weight: 1
    - value: quay.io/prometheus/node-exporter:v1.6.1
      weight: 1
    - value: 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-network-policy-agent:v1.1.5-eksbuild.1
      weight: 1
    - value: 066635153087.dkr.ecr.il-central-1.amazonaws.com/amazon-k8s-cni:v1.19.0
      weight: 1
    - value: public.ecr.aws/karpenter/controller@sha256:9b31039d45613ac22a104b8d48eca9dcdeff93e525bd473c811dfd3502e58c69
      weight: 1
    - value: docker.io/bitnami/redis:7.2.3-debian-11-r2
      weight: 1
    - value: registry.k8s.io/ingress-nginx/controller@sha256:9724476b928967173d501040631b23ba07f47073999e80e34b120e8db5f234d5
      weight: 1
    - value: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.5
      weight: 1
    - value: 465927837118.dkr.ecr.us-east-1.amazonaws.com/greptimeteam/dashboard-private:60b6c415-dashboard-test
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/external-resizer:v1.11.1-eks-1-30-10
      weight: 1
    - value: 066635153087.dkr.ecr.il-central-1.amazonaws.com/eks/kube-proxy:v1.30.6-minimal-eksbuild.3
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner:v4.0.0-eks-1-29-7
      weight: 1
    - value: docker.io/grafana/loki:2.9.5
      weight: 1
    - value: registry.k8s.io/ingress-nginx/controller@sha256:5b161f051d017e55d358435f295f5e9a297e66158f136321d9b04520ec6c48a3
      weight: 1
    - value: docker.io/bitnami/etcd:3.5.9-debian-11-r4
      weight: 1
    type: weighted_preset
  name: image
  type: String
- dist:
    preset:
    - value: 10.0.162.77:10250
      weight: 1
    - value: 10.0.162.53:10250
      weight: 1
    - value: 10.0.175.164:10250
      weight: 1
    - value: 10.0.169.179:10250
      weight: 1
    - value: 10.0.166.131:10250
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: kubelet
  name: job
  type: String
- dist:
    type: constant_string
    value: /metrics/cadvisor
  name: metrics_path
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: b153517b90d7f85f7e77235f1185274abddd12d14c387b92ca7aa62cdfc539aa
      weight: 1
    - value: 83723ef720c1c95ed4228fe59e3667ef50d55e099b3ce07316f865a611984954
      weight: 1
    - value: b9afbc1ca38342723e7948d48f7033a976dcf5c4bb9bd2bb80d422fb4e74d5fe
      weight: 1
    - value: b4022f119f874de41bfe389c5c7d6806950f17b62b0d4ae283bf1a2fbbb7c37c
      weight: 1
    - value: 811ef3eae0d0be45c7eca8ed72645697cd15d95135e4d0b373da9834f46d8df1
      weight: 1
    - value: 9684ead7dd6dc36ca81c8dc7f9fb363bf33ea7936e34535850013ee0510776f6
      weight: 1
    - value: 1225305fe001e9c73921d32581b7adfafc6768f8190bfcbfc7019f2b0ca829c8
      weight: 1
    - value: da29c54ef3b1a6e02a9263d5ebab7dd1c82a4faf1b960ba48e69df0169f800c5
      weight: 1
    - value: 7feadb35f38918f16e55b9ed4c66016d22e6cc80110884121553ec644e6daf79
      weight: 1
    - value: 2d1e5791229bb644f302c4c2a49cabf0bac0f3da3ec3888ea4f5ee9976a1ec54
      weight: 1
    - value: 235917935b4445f72612f412fc4af6d4bb13095e569af31a58ad81d566dd8b08
      weight: 1
    - value: b871741ed5ea0e1f46cb4284b4ae4e7ed075ef7c55bab71b61ec50303258b7dd
      weight: 1
    - value: e42c2c2ab520ab37bc80a345c24138e95673119aa4f22722a204fed5f696e06c
      weight: 1
    - value: fb07b4f0ca826ddd9ac17ed1cf1830c6ee3a1859ecb2297585cea7a2f586e160
      weight: 1
    - value: 4e6342fa40cf26acb5a179ffca1fee92af0bb4b06c350efbd303587289c1e5d0
      weight: 1
    - value: a63c7025308704077ad95c90b2a2c7a960eb3c67bbeb82c4ae4ead66fc268d7b
      weight: 1
    - value: f86339b3bd92c3d5400047abd59ec93ef3766219c83e9053d3b556166d981e46
      weight: 1
    - value: 59e0ac6d05d16781e8528879233691c6a0f56212de951965c350b5192a592236
      weight: 1
    - value: 46d9ab51549fbdb7a72ac217a7ab6475a80ee2ae811e0156b0334e91fa3a263a
      weight: 1
    type: weighted_preset
  name: name
  type: String
- dist:
    preset:
    - value: kafka
      weight: 1
    - value: argo-cd
      weight: 1
    - value: kube-system
      weight: 1
    - value: tempo
      weight: 1
    - value: etcd
      weight: 1
    - value: debug
      weight: 1
    - value: vector
      weight: 1
    - value: monitoring
      weight: 1
    - value: internal-greptimedb-standalone
      weight: 1
    - value: karpenter
      weight: 1
    - value: gcp
      weight: 1
    - value: dedicated-etcd
      weight: 1
    - value: bytebase
      weight: 1
    - value: ingress-nginx
      weight: 1
    - value: greptimedb
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: loki
      weight: 1
    - value: internal-ingress-nginx
      weight: 1
    - value: greptimedb-standalone
      weight: 1
    - value: external-dns
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: kafka-controller-0
      weight: 1
    - value: argo-cd-argocd-server-6c544f855d-4g99m
      weight: 1
    - value: ebs-csi-node-c24t2
      weight: 1
    - value: ebs-csi-node-297wb
      weight: 1
    - value: tempo-0
      weight: 1
    - value: etcd-0
      weight: 1
    - value: debug-796b745495-bcz88
      weight: 1
    - value: ebs-csi-node-2ffjx
      weight: 1
    - value: vector-dbg5j
      weight: 1
    - value: vector-qwpl5
      weight: 1
    - value: prometheus-prometheus-node-exporter-bzhjw
      weight: 1
    - value: internal-greptimedb-standalone-0
      weight: 1
    - value: prometheus-prometheus-node-exporter-bpscm
      weight: 1
    - value: aws-node-6d2l8
      weight: 1
    - value: karpenter-56f457fcb9-x9k7c
      weight: 1
    - value: gcp-redis-master-0
      weight: 1
    - value: efs-csi-node-x2ht5
      weight: 1
    - value: aws-load-balancer-controller-6896d97fcf-897cz
      weight: 1
    - value: etcd-1
      weight: 1
    - value: bytebase-0
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kubelet
  name: service
  type: String
